###
GET http://localhost:5000/products




###
GET http://localhost:5000/products/


###
POST http://localhost:5000/user/
Content-Type: application/json

{
    "name":"Jayanthi",
    "total":500,
    "discount":50,
    "netAmount":450
}